### PR TITLE
APIからの情報の取得をxmlからjsonに変えたい。

### PR DESCRIPTION
**Pull request by enokawa**
% rails s
=> Booting WEBrick
=> Rails 4.1.6 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
[2014-10-28 15:24:55] INFO  WEBrick 1.3.1
[2014-10-28 15:24:55] INFO  ruby 2.1.2 (2014-05-08) [x86_64-darwin13.0]
[2014-10-28 15:24:55] INFO  WEBrick::HTTPServer#start: pid=16428 port=3000

Started GET "/" for 127.0.0.1 at 2014-10-28 15:25:00 +0900
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".\* FROM "schema_migrations"
Processing by KarutaController#index as HTML
Completed 500 Internal Server Error in 130ms

NoMethodError (undefined method `elements' for #<Hash:0x007fa06bdcb640>):
  app/models/doraemon_question.rb:4:in`question'
  app/controllers/karuta_controller.rb:6:in `index'

  Rendered /Users/enoyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.6ms)
  Rendered /Users/enoyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /Users/enoyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /Users/enoyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (25.3ms)

### CODE REVIEW

**Comment by himajin315** [comment]
`NoMethodError (undefined method elements' for #<Hash:0x007fa06bdcb640>)` だね。
`doraemon_question.rb` にある`question`メソッドに`binding.pry`を入れたらいいと思います。

``` ruby
  def question
    binding.pry
    api_response.elements['response/result/doc/Body']
  end
```

`print api_response`して、どうにかしてBodyを取得したらいいですね。
`api_response[response][result][doc][Body]`っぽいけど。

**Comment by himajin315** [comment]
お、行けそうな感じがする((o(´∀｀)o))ﾜｸﾜｸ

**Comment by himajin315** [comment]
動いたみたいだからマージしてもいいのかな。

**Comment by enokawa** [comment]
@himajin315 お願いします！

**Pull request merged**
